#!/bin/bash

# Use a custom host name, for loading config files etc, if the file exists
function custom_hostname() {
	local output
	if [[ -s "$HOME/.bc-hostname" ]]; then
		output=$(cat "$HOME/.bc-hostname" 2>/dev/null | tr -d '\n\r')
	fi
	if [[ -z "$output" ]]; then
		output=$(hostname 2>/dev/null || echo "unknown")
	fi
	export HOSTNAME="$output"
}
