#!/bin/bash

# Use a custom host name, for loading config files etc, if the file exists
function custom_hostname() {
  local output
	if [[ -s "$HOME/.bc-hostname" ]]; then
    # echo "Exists and not empty"
    output=$(cat $HOME/.bc-hostname)
  else
    # echo "Doesn't exist or is empty"
    output=$(hostname)
  fi
  export HOSTNAME=$output
}
