#!/bin/bash

function dump_description {
   echo '======================================================'
   for i in $(seq 0 2); do echo ''; done
   echo $1
   for i in $(seq 0 2); do echo ''; done
   echo '======================================================'
} 

dump_description "bb release"
/home/stepblk/.toolbox/bin/brazil-build release

if [ $? != 0 ]
then
    dump_description '"bb release" failed'
    return
fi

dump_description "brazil ws env update"
/home/stepblk/.toolbox/bin/brazil ws env update

if [ $? != 0 ]
then
    dump_description '"brazil ws env update" failed'
    return
fi

dump_description "sudo runCommand -a Activate -e LilyConsole"
sudo /apollo/bin/runCommand -a Activate -e LilyConsole

if [ $? != 0 ]
then
    dump_description '"sudo runCommand -a Activate -e LilyConsole" failed'
    return
fi
