# AmazonCloudDesk/zshenv

# echo "Running $HOSTNAME/zshenv"

##############################################################################

export BRAZIL_WORKSPACE_DEFAULT_LAYOUT=short

export AUTO_TITLE_SCREENS="NO"

export PATH=/apollo/env/NodeJS/bin:$PATH:$HOME/.local/bin:$HOME/bin
