# JungleFort/zshenv

echo "Running $HOSTNAME/zshenv"

##############################################################################

export BRAZIL_WORKSPACE_DEFAULT_LAYOUT=short

export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home

### $ brew install rbenv libyaml libffi

# libffi is keg-only, which means it was not symlinked into /usr/local,
# because macOS already provides this software and installing another version in
# parallel can cause all kinds of trouble.

# For compilers to find libffi you may need to set:
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export CPPFLAGS="-I/usr/local/opt/libffi/include"
# For pkg-config to find libffi you may need to set:
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

# AWS Account ID, used by AWSLockeConsoleCDK
# AWSLockeConsoleCDK = 776501286848
export AWS_ACCOUNT_ID=776501286848

# TangerineBox Setup for local dev
export USE_WEBPACK_DEV_SERVER_ASSETS=true
